config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root 'home#index'
  get 'home/index'

  resources :users, only: [:show, :edit, :update]
  resources :posts, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user

	has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord

	has_many :posts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def new
		
	end

	def create
		Post.create(post_params)
		redirect_to root_path
	end


	private

	def post_params
		params.require(:post).permit(:description, :image, :user_id)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show	
	end

	def edit
		@user = User.find(params[:id])	
	end

	def update
		current_user.update(user_params)
		redirect_to current_user
	end


	private
	
	def user_params
		params.require(:user).permit(:username, :name, :website, :bio, :email, :phone, :gender)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instuigram</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <nav class="navbar navbar-light bg-light d-flex">
      <div class="container">
        <div class="logo">
          <a class="navbar-brand" href="/home/index">
            <%= fa_stacked_icon "camera inverse", base: "circle"%>
            Instagram
          </a>
        </div>
        <div class="m-auto">
          <form class="form-inline search-form">
            <input class="form-control mr-sm-2" type="search" placeholder="@search" aria-label="Search">
          </form>
        </div>
        <div class="user-section">
          <a><i class="fa fa-compass"></i></a>
          <a><i class="fa fa-heart"></i></a>
          
          <% if user_signed_in? %>
             <a href="<%= user_path(current_user)%>">
              <i class="fa fa-user"></i>
             </a>
          <% else %>
            <a href="<%= new_user_session_path%>">
               <i class="fa fa-sign-in"></i>
            </a>
         <% end %>

        </div>
      </div>
    </nav>

    
    <main class="container" style="min-height: 500px;">

      <%= yield %>
    </main>

    
    <footer class="container footer">
      <nav class="navbar d-flex">
        <ul>
          <li><%= link_to 'ABOUT US', root_path %></li>
          <li><%= link_to 'SUPPORT', root_path %> </li>
          <li><%= link_to 'PRESS', root_path %></li>
          <li><%= link_to 'API', root_path %></li>
          <li><%= link_to 'JOBS', root_path %></li>
          <li><%= link_to 'PRIVACY', root_path %></li>
          <li><%= link_to 'TERMS', root_path %></li>
          <li><%= link_to 'DIRECTORY', root_path %></li>
          <li><%= link_to 'PROFILES', root_path %></li>
          <li><%= link_to 'HASHTAGS', root_path %></li>
          <li><%= link_to 'LANGUAGE', root_path %></li>
        </ul>
        <p> © 2019 INSTAGRAM </p>
      </nav>
    </footer>
  </body>
</html>

app/views/posts/new.html.erb
<%= form_for Post.new do |f| %>
  <div class="form-group">
    <%= f.text_field :description %>
  </div>
  <div class="form-group">
    <%= f.file_field :image %>
  </div>
  <div class="form-group">
    <%= f.text_field :user_id, value: current_user.id, class:'d-none'%>
  </div>
  <br>
  <div class="text-center">
    <%= f.submit 'Create Post', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="user-edit-page">
	<div class="actions">
		<div class="user-edit-page">
			<div class="actions">
				<div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
					<a class="nav-link active" data-toggle="pill" href="#v-pills-home" role="tab" aria-selected="true">Edit Profile</a>
					<a class="nav-link" data-toggle="pill">Change Password</a>
					<a class="nav-link" data-toggle="pill">Authorized Applications</a>
					<a class="nav-link" data-toggle="pill">Email and SMS</a>
					<a class="nav-link" data-toggle="pill">Manage Contacts</a>
					<a class="nav-link" data-toggle="pill">Privacy and Security</a>
				</div>
			</div>
			<div class="details tab-content">
				<div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
					<!-- Form edit profile -->
				</div>
			</div>
		</div>
	</div>
	
	<div class="details">
		<%= form_with model: current_user, local: true, html: {class: "form-horizontal form-edit-user"} do |f| %>
		<div class="form-group row">
			<div class="col-sm-3 col-form-label">
				<img class="avatar" src="https://instuigram-avatar.jpg">
			</div>
			<div class="col-sm-9">
				<p class="username"><%=current_user.username %></p>
				<a class="change-photo" href="">Change Profile Photo</a>
			</div>
		</div>
		<div class="form-group row">
			<%= f.label :name, class: 'col-sm-3 col-form-label' %>
			<div class="col-sm-9">
				<%= f.text_field :name, class: 'form-control' %>
			</div>
		</div>
		<div class="form-group row">
			<%= f.label :username, class: 'col-sm-3 col-form-label' %>
			<div class="col-sm-9">
				<%= f.text_field :username, class: 'form-control' %>
			</div>
		</div>
		<div class="form-group row">
			<%= f.label :website, class: 'col-sm-3 col-form-label' %>
			<div class="col-sm-9">
				<%= f.text_field :website, class: 'form-control' %>
			</div>
		</div>
		<div class="form-group row">
			<%= f.label :bio, class: 'col-sm-3 col-form-label' %>
			<div class="col-sm-9">
				<%= f.text_area :bio, class: 'form-control' %>
			</div>
		</div>
		<div class="form-group row">
			<%= f.label :email, class: 'col-sm-3 col-form-label' %>
			<div class="col-sm-9">
				<%= f.text_field :email, class: 'form-control' %>
			</div>
		</div>
		<div class="form-group row">
			<%= f.label :phone, class: 'col-sm-3 col-form-label' %>
			<div class="col-sm-9">
				<%= f.text_field :phone, class: 'form-control' %>
			</div>
		</div>
		<div class="form-group row">
			<%= f.label :gender, class: 'col-sm-3 col-form-label' %>
			<div class="col-sm-9">
				<%= f.text_field :gender, class: 'form-control' %>
			</div>
		</div>
		<div class="form-group row">
			<div class="col-sm-3">
			</div>
			<div class="col-sm-9">
				<%= f.submit "Submit", class: 'btn btn-primary' %>
			</div>
		</div>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="profile row">
    <div class="col-md-4 avatar">
      <div class="wrapper">
        <img src="https://instuigram-avatar.jpg">
      </div>
    </div>
    
    <div class="col-md-8 basic-info">
      <div class="user-wrapper">
        <h2 class="username"><%= current_user.username %></h2>
        <a class="edit-profile" href="<%= edit_user_path(current_user) %>">
         <button>Edit Profile</button>
       </a>
     </div>
     <ul class="posts">
      <li><span>0</span> posts</li>
      <li><span>0</span> followers</li>
      <li><span>0</span> following</li>
    </ul>
    <h2 class="name"><%= current_user.name %></h2>
    <%=link_to current_user.website, current_user.website, class:  'website' %>
  </div>
</div>
</div>

<div class="user-tabs">
  <a class="tab active" href="/posts/new">
    <i class="fa fa-th"></i>
    POSTS
  </a>
  <a class="tab" href="">
    <i class="fa fa-tv"></i>
    IGTV
  </a>
  <a class="tab" href="">
    <i class="fa fa-bookmark"></i>
    SAVED
  </a>
  <a class="tab" href="">
    <i class="fa fa-tag"></i>
    TAGGED
  </a>
</div>

<div class="user-images">
  <div class="wrapper">
    <img src="your_image_url">
  </div>
  <div class="wrapper">
    <img src="your_image_url">
  </div>
  <div class="wrapper">
    <img src="your_image_url">
  </div>
</div>